include: package:lint/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "lib/core/injections/locator.config.dart"

  errors:
    avoid_classes_with_only_static_members: ignore
    invalid_annotation_target: ignore