name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  auto_route: ^8.1.3
  collection: ^1.18.0
  cross_connectivity: ^3.2.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  email_validator: ^2.1.17
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  # flutter_svg_provider:
  #   git:
  #     ref: fix/deps
  #     url: https://github.com/andreasgangso/flutter_svg_provider.git
  fluttertoast: ^8.2.5
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.1
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  change_app_package_name: ^1.1.0
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lint: ^2.3.0
  sizer: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/animations/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true
