name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  auto_route: ^7.8.3
  collection: ^1.17.2
  cross_connectivity: ^3.0.5
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.0
  dio: ^5.3.2
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_svg_provider:
    git:
      ref: fix/deps
      url: https://github.com/andreasgangso/flutter_svg_provider.git
  fluttertoast: ^8.2.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hooks_riverpod: ^2.4.0
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.7.0
  package_info_plus: ^4.1.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  lint: ^2.1.2
  sizer: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/animations/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true
